add error handling and typo code

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -17,7 +17,8 @@ if [ ! -f "${GUESTADDITIONS}" ] ; then
         GUESTADDITIONS=${GUESTADDITIONS_PATH}
         echo "GUESTADDITIONS=${GUESTADDITIONS_PATH}"
     else
-        echo "Can't find GuestAdditions ISO, find manually and update vars.sh with the right path"
+        echo "ERROR: Can't find GuestAdditions ISO, find manually and update vars.sh with the right path. Aborting..."
+        exit 1
     fi
 
 fi
@@ -78,7 +79,7 @@ VBoxManage startvm ${NAME} --type gui
 # This only really caters for the common case. If you have problems, please
 # discover your host's IP address and adjust accordingly.
 IP=`echo ${NATNET} | sed -nE 's/^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}).*/\1/p'`
-IP=${IP}".4"
+IP=${IP}".3"
 
 
 # Tring to ping the IP if not reachable set error
